bound_ini_normalize_base: none
constant_start_epoch: 100000
data_sampler: latin_hypercube
device: cuda:0
epochs: 30000
final_lr: 0.0001
final_record_epoch: 100
lr: 0.001
lr_scheduler: cosine
n_boundary: 250
n_initial: 250
n_internal: 10000
n_losses: 2
name: pcgrad_30000_full
network_initialization: xavier
normalize_base: none
optimizer: Adam
random_seed: 52943
record_epoch_loss: true
record_final_losses: true
record_iteration_loss: false
record_learning_rate: true
save_epoch: 15000
save_path: ./PINN_trained/Burgers/
simulation_time: 1.0
update_training_data: true
validation_epoch_frequency: 1
warmup_epoch: 100
x_end: 1.0
x_start: -1.0
